//! Multi-session experience consolidation pass.
//!
//! ## What this adds
//!
//! While `promote.rs` distils one session deposit file at a time, `consolidate.rs`
//! compares records across multiple sessions side-by-side to discover recurrent
//! procedural patterns, cross-session architectural decisions, and common blockers.
//!
//! Inspired by the `experience` pass from `ai-memory` (analyzed in
//! `reports/2026-09-14-ai-memory-akita-comparado-ulpia.md`), with two crucial
//! architectural properties:
//!
//! 1. **Code-enforced multi-session invariant:** A recurrent pattern proposal MUST cite
//!    at least two distinct session IDs, and the validator verifies in Rust code that
//!    both sessions actually exist in the recorded session history. A model hallucinating
//!    a session or repeating a single session twice is rejected deterministically.
//! 2. **Independent three-lens review gate:** The candidates generated by the experience
//!    pass are evaluated through the same three independent lenses as any promotion
//!    (contradiction, duplication, scope) against the base before anything is written.

use std::collections::HashSet;
use std::path::Path;

use crate::classify::Classifier;
use crate::handoff;
use crate::memory::Memory;
use crate::promote::{
    self, ask_model, evidence_for, parse_review, read_rejections, record_rejection, review_prompt,
    Decided, Lens, PriorRejection, Proposal, Review, CAPTURED,
};

/// Distilled experience from one session.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SessionExperience {
    pub session: String,
    pub agent: String,
    pub task: String,
    pub decisions: Vec<String>,
    pub blockers: Vec<String>,
    pub next_steps: Vec<String>,
    pub refusals: Vec<String>,
}

impl SessionExperience {
    pub fn format_for_prompt(&self) -> String {
        let mut out = format!("SESSION: {}\n", self.session);
        if !self.task.is_empty() {
            out.push_str(&format!("  Task: {}\n", self.task));
        }
        if !self.decisions.is_empty() {
            out.push_str("  Decisions:\n");
            for d in &self.decisions {
                out.push_str(&format!("    - {}\n", d));
            }
        }
        if !self.blockers.is_empty() {
            out.push_str("  Blockers:\n");
            for b in &self.blockers {
                out.push_str(&format!("    - {}\n", b));
            }
        }
        if !self.refusals.is_empty() {
            out.push_str("  Refused questions:\n");
            for r in &self.refusals {
                out.push_str(&format!("    - {}\n", r));
            }
        }
        out
    }
}

/// Gathers experience records across past sessions for an agent.
pub fn gather_experience(root: &Path, agent: &str, max_sessions: usize) -> Vec<SessionExperience> {
    let mut out = Vec::new();
    let mut seen_sessions = HashSet::new();

    // 1. Read handoffs from .kb/sessions/
    let handoffs = handoff::list_handoffs(root, Some(agent));
    for h in handoffs.into_iter().take(max_sessions) {
        seen_sessions.insert(h.session.clone());
        out.push(SessionExperience {
            session: h.session,
            agent: h.agent,
            task: h.task,
            decisions: h.decisions,
            blockers: h.blockers,
            next_steps: h.next_steps,
            refusals: Vec::new(),
        });
    }

    // 2. Read session deposits from <agent>/inbox/*-session-*.md
    let agent_root = crate::write::agent_root(root, agent);
    let inbox = agent_root.join(promote::DEPOSIT);
    if let Ok(entries) = std::fs::read_dir(inbox) {
        for entry in entries.flatten() {
            let p = entry.path();
            let name = p.file_name().and_then(|n| n.to_str()).unwrap_or("");
            if name.contains("-session-") && name.ends_with(".md") {
                if let Some(sess_part) = name.strip_suffix(".md").and_then(|s| s.split("-session-").nth(1)) {
                    let sess_id = sess_part.to_string();
                    if out.len() >= max_sessions && seen_sessions.contains(&sess_id) {
                        continue;
                    }
                    if let Ok(text) = std::fs::read_to_string(&p) {
                        let refusals = parse_deposit_refusals(&text);
                        if let Some(existing) = out.iter_mut().find(|e| e.session == sess_id) {
                            existing.refusals = refusals;
                        } else if out.len() < max_sessions {
                            seen_sessions.insert(sess_id.clone());
                            out.push(SessionExperience {
                                session: sess_id,
                                agent: agent.to_string(),
                                task: String::new(),
                                decisions: Vec::new(),
                                blockers: Vec::new(),
                                next_steps: Vec::new(),
                                refusals,
                            });
                        }
                    }
                }
            }
        }
    }

    out
}

/// Parses refused questions out of a captured deposit markdown.
fn parse_deposit_refusals(text: &str) -> Vec<String> {
    let mut refusals = Vec::new();
    let mut in_refusals = false;
    for line in text.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with("## Refusals") || trimmed.starts_with("# Refusals") {
            in_refusals = true;
            continue;
        } else if trimmed.starts_with('#') {
            in_refusals = false;
            continue;
        }
        if in_refusals && trimmed.starts_with("- ") {
            if let Some(q) = trimmed.strip_prefix("- ") {
                refusals.push(q.trim().to_string());
            }
        }
    }
    refusals
}

/// Builds the consolidation prompt presenting multiple session experiences side-by-side.
pub fn consolidation_prompt(agent: &str, experiences: &[SessionExperience]) -> String {
    let mut out = String::new();
    out.push_str(
        "You are reading experience and handoff records from MULTIPLE past sessions for an agent.\n\
         Your job is to identify RECURRENT patterns, cross-session architectural decisions,\n\
         or proven procedural conventions that emerged across AT LEAST TWO different sessions.\n\n",
    );
    out.push_str(&format!("THE AGENT: {agent}\n\n"));
    out.push_str("PAST SESSIONS HISTORY:\n---\n");
    for exp in experiences {
        out.push_str(&exp.format_for_prompt());
        out.push('\n');
    }
    out.push_str("---\n\n");
    out.push_str(
        "RULES.\n\
         - Propose nothing rather than something speculative. Only propose knowledge that is \
           genuinely confirmed across multiple sessions.\n\
         - **Multi-session requirement:** Every proposed note MUST cite at least two distinct \
           session IDs from the history above in its `sources:` line (e.g. `sources: s-1, s-2`). \
           An observation appearing in only one session is an incident, not a reusable pattern.\n\
         - One note answers one question.\n\
         - `keys` are the words a real question would use, in Portuguese and English.\n\
         - `summary` says what the note is ABOUT in one line, no trailing period.\n\
         - **No em dashes and no en dashes**, anywhere. Use a hyphen, a colon, or a comma.\n\n\
         FORMAT. Zero or more blocks, exactly like this:\n\n\
         PROPOSAL\n\
         slug: short-kebab-case-name\n\
         folder: knowledge/<subfolder>\n\
         summary: one line description\n\
         keys: term, term, term\n\
         sources: session_id_1, session_id_2\n\
         body:\n\
         the markdown body of the note\n\
         END\n\n\
         If nothing here represents a confirmed cross-session pattern, output NOTHING.\n",
    );
    out
}

/// A proposal generated by the multi-session consolidation pass.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ConsolidatedProposal {
    pub agent: String,
    pub slug: String,
    pub folder: String,
    pub summary: String,
    pub keys: Vec<String>,
    pub sources: Vec<String>,
    pub body: String,
}

/// Parses the output of the consolidation promoter.
pub fn parse_consolidated_proposals(reply: &str, agent: &str) -> Vec<ConsolidatedProposal> {
    let mut out = Vec::new();
    let mut lines = reply.lines().peekable();

    while let Some(line) = lines.next() {
        if line.trim() != "PROPOSAL" {
            continue;
        }
        let (mut slug, mut folder, mut summary) = (String::new(), String::new(), String::new());
        let mut keys: Vec<String> = Vec::new();
        let mut sources: Vec<String> = Vec::new();
        let mut body = String::new();
        let mut in_body = false;

        for l in lines.by_ref() {
            let t = l.trim();
            if t == "END" {
                break;
            }
            if in_body {
                body.push_str(l);
                body.push('\n');
                continue;
            }
            if let Some(v) = t.strip_prefix("slug:") {
                slug = v.trim().to_string();
            } else if let Some(v) = t.strip_prefix("folder:") {
                folder = v.trim().to_string();
            } else if let Some(v) = t.strip_prefix("summary:") {
                summary = v.trim().trim_end_matches('.').to_string();
            } else if let Some(v) = t.strip_prefix("keys:") {
                keys = v
                    .split(',')
                    .map(|k| k.trim().trim_matches('`').to_string())
                    .filter(|k| !k.is_empty())
                    .collect();
            } else if let Some(v) = t.strip_prefix("sources:") {
                sources = v
                    .split(',')
                    .map(|s| s.trim().to_string())
                    .filter(|s| !s.is_empty())
                    .collect();
            } else if t == "body:" {
                in_body = true;
            }
        }

        if slug.is_empty() || summary.is_empty() || keys.is_empty() || body.trim().is_empty() {
            continue;
        }

        out.push(ConsolidatedProposal {
            agent: agent.to_string(),
            slug,
            folder: if folder.is_empty() { "knowledge".into() } else { folder },
            summary,
            keys,
            sources,
            body: body.trim().to_string(),
        });
    }

    out
}

/// Validates that a proposal cites at least 2 distinct session IDs that actually exist
/// in the provided available sessions set.
pub fn validate_multi_session_evidence(
    proposal: &ConsolidatedProposal,
    available_sessions: &HashSet<String>,
) -> Result<(), String> {
    let distinct: HashSet<&str> = proposal
        .sources
        .iter()
        .map(|s| s.trim())
        .filter(|s| !s.is_empty())
        .collect();

    if distinct.len() < 2 {
        return Err(format!(
            "multi-session consolidation requires at least 2 distinct sessions, found {}: {:?}",
            distinct.len(),
            proposal.sources
        ));
    }

    for s in &distinct {
        if !available_sessions.contains(*s) {
            return Err(format!(
                "cited session '{s}' does not exist in recorded session history"
            ));
        }
    }

    Ok(())
}

/// Outcome of a consolidation run.
#[derive(Debug, Default)]
pub struct ConsolidationOutcome {
    pub agent: String,
    pub sessions_consulted: usize,
    pub proposals_generated: usize,
    pub rejected_evidence: Vec<(String, String)>,
    pub decided: Vec<Decided>,
}

impl ConsolidationOutcome {
    pub fn written(&self) -> usize {
        self.decided.iter().filter(|d| d.written.is_some()).count()
    }

    pub fn admitted(&self) -> usize {
        self.decided.iter().filter(|d| d.accepted()).count()
    }

    pub fn refused(&self) -> usize {
        self.decided.iter().filter(|d| !d.accepted()).count()
    }

    pub fn as_json(&self) -> crate::json::Value {
        let mut obj = crate::json::Value::obj();
        obj.set("agent", crate::json::Value::Str(self.agent.clone()));
        obj.set(
            "sessions_consulted",
            crate::json::Value::Num(self.sessions_consulted as f64),
        );
        obj.set(
            "proposals_generated",
            crate::json::Value::Num(self.proposals_generated as f64),
        );
        obj.set("written", crate::json::Value::Num(self.written() as f64));
        obj.set("admitted", crate::json::Value::Num(self.admitted() as f64));
        obj.set("refused", crate::json::Value::Num(self.refused() as f64));

        let mut rej_arr = Vec::new();
        for (slug, reason) in &self.rejected_evidence {
            let mut r_obj = crate::json::Value::obj();
            r_obj.set("slug", crate::json::Value::Str(slug.clone()));
            r_obj.set("reason", crate::json::Value::Str(reason.clone()));
            rej_arr.push(r_obj);
        }
        obj.set("rejected_evidence", crate::json::Value::Arr(rej_arr));

        let mut dec_arr = Vec::new();
        for d in &self.decided {
            let mut d_obj = crate::json::Value::obj();
            d_obj.set("slug", crate::json::Value::Str(d.proposal.slug.clone()));
            d_obj.set("accepted", crate::json::Value::Bool(d.accepted()));
            d_obj.set("source", crate::json::Value::Str(d.proposal.source.clone()));
            if let Some(p) = &d.written {
                d_obj.set("written", crate::json::Value::Str(p.display().to_string()));
            }
            let rev_arr: Vec<crate::json::Value> = d
                .reviews
                .iter()
                .map(|r| {
                    let mut ro = crate::json::Value::obj();
                    ro.set("lens", crate::json::Value::Str(r.lens.name().to_string()));
                    ro.set("accept", crate::json::Value::Bool(r.accept));
                    ro.set("reason", crate::json::Value::Str(r.reason.clone()));
                    ro
                })
                .collect();
            d_obj.set("reviews", crate::json::Value::Arr(rev_arr));
            dec_arr.push(d_obj);
        }
        obj.set("decided", crate::json::Value::Arr(dec_arr));
        obj
    }
}

/// Executes a consolidation pass across past sessions for an agent.
pub fn run(
    memory: &mut Memory,
    fleet_root: &Path,
    agent: &str,
    synthesizer: &Classifier,
    reviewer: &Classifier,
    max_sessions: usize,
    top: usize,
    dry_run: bool,
    today: &str,
) -> ConsolidationOutcome {
    let mut outcome = ConsolidationOutcome {
        agent: agent.to_string(),
        ..Default::default()
    };

    let experiences = gather_experience(fleet_root, agent, max_sessions);
    outcome.sessions_consulted = experiences.len();

    if experiences.len() < 2 {
        // A pattern cannot be cross-session if fewer than 2 sessions exist.
        return outcome;
    }

    let available_sessions: HashSet<String> = experiences
        .iter()
        .map(|e| e.session.clone())
        .collect();

    let prompt = consolidation_prompt(agent, &experiences);
    let Some(reply) = ask_model(synthesizer, fleet_root, &prompt) else {
        return outcome;
    };

    let proposals = parse_consolidated_proposals(&reply, agent);
    outcome.proposals_generated = proposals.len();

    let mut prior_rejections = read_rejections(fleet_root);

    for cons_proposal in proposals {
        // 1. Code-level invariant check: must cite at least 2 valid, distinct sessions.
        if let Err(reason) = validate_multi_session_evidence(&cons_proposal, &available_sessions) {
            outcome
                .rejected_evidence
                .push((cons_proposal.slug.clone(), reason));
            continue;
        }

        // 2. Folder kind must be Memory (ADR-0031)
        let kind = crate::index::kind_of(&cons_proposal.folder);
        if kind != crate::index::Kind::Memory {
            outcome.rejected_evidence.push((
                cons_proposal.slug.clone(),
                format!("target folder is {}-kind, memory only", kind.label()),
            ));
            continue;
        }

        let proposal = Proposal {
            agent: cons_proposal.agent.clone(),
            slug: cons_proposal.slug.clone(),
            folder: cons_proposal.folder.clone(),
            summary: cons_proposal.summary.clone(),
            keys: cons_proposal.keys.clone(),
            body: cons_proposal.body.clone(),
            source: cons_proposal.sources.join(", "),
        };

        // 3. Check prior rejections and deterministic repetition filter
        let proposal_priors: Vec<&PriorRejection> = prior_rejections
            .iter()
            .filter(|r| r.agent.eq_ignore_ascii_case(&proposal.agent) && r.slug == proposal.slug)
            .collect();

        if let Some(repeat) = proposal_priors.iter().find(|r| r.count >= 3) {
            let lens = match repeat.lens.as_str() {
                "contradiction" => Lens::Contradiction,
                "scope" => Lens::Scope,
                _ => Lens::Duplication,
            };
            let decided = Decided {
                proposal,
                reviews: vec![Review {
                    lens,
                    accept: false,
                    reason: format!(
                        "deterministic repetition filter: refused {} times (last {}): {}",
                        repeat.count, repeat.last_seen, repeat.reason
                    ),
                }],
                written: None,
            };
            if !dry_run {
                record_rejection(fleet_root, &decided, today);
                prior_rejections = read_rejections(fleet_root);
            }
            outcome.decided.push(decided);
            continue;
        }

        // 4. Query independent input from the base
        let evidence = evidence_for(memory, &proposal, top);

        // 5. Evaluate through the 3 reviewer lenses
        let mut reviews = Vec::new();
        let mut reachable = true;
        for lens in Lens::ALL {
            let prior_for_lens = proposal_priors
                .iter()
                .find(|r| r.lens.eq_ignore_ascii_case(lens.name()))
                .copied();
            let p = review_prompt(&proposal, &evidence, lens, prior_for_lens);
            match ask_model(reviewer, fleet_root, &p) {
                Some(r) => reviews.push(parse_review(&r, lens)),
                None => {
                    reachable = false;
                    break;
                }
            }
        }

        if !reachable {
            continue;
        }

        let mut decided = Decided {
            proposal,
            reviews,
            written: None,
        };

        if decided.accepted() && !dry_run {
            let spec = crate::write::Note {
                summary: decided.proposal.summary.clone(),
                keys: decided.proposal.keys.clone(),
                folder: decided.proposal.folder.clone(),
                provenance: "agent".into(),
                stage: CAPTURED.into(),
                captured_from: Some(decided.proposal.source.clone()),
                body: decided.proposal.body.clone(),
            };
            match crate::write::note(fleet_root, &decided.proposal.agent, &decided.proposal.slug, &spec) {
                Ok(w) => {
                    decided.written = Some(w.note);
                    let _ = memory.reread();
                }
                Err(e) if e.is_refusal() => {
                    decided.reviews.push(Review {
                        lens: Lens::Scope,
                        accept: false,
                        reason: format!("refused at the write: {e}"),
                    });
                    record_rejection(fleet_root, &decided, today);
                    prior_rejections = read_rejections(fleet_root);
                }
                Err(_) => {}
            }
        } else if !decided.accepted() && !dry_run {
            record_rejection(fleet_root, &decided, today);
            prior_rejections = read_rejections(fleet_root);
        }

        outcome.decided.push(decided);
    }

    outcome
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_consolidated_proposals_extracts_all_fields() {
        let reply = "\
PROPOSAL
slug: atomic-file-persistence
folder: knowledge/systems
summary: Always write temporary file before atomic rename
keys: atomic, write, rename, persistence
sources: s-phase1, s-phase2
body:
When updating files that must remain valid across crashes, write to a .tmp file first.
END
";
        let parsed = parse_consolidated_proposals(reply, "zed");
        assert_eq!(parsed.len(), 1);
        assert_eq!(parsed[0].slug, "atomic-file-persistence");
        assert_eq!(parsed[0].folder, "knowledge/systems");
        assert_eq!(parsed[0].summary, "Always write temporary file before atomic rename");
        assert_eq!(parsed[0].keys, vec!["atomic", "write", "rename", "persistence"]);
        assert_eq!(parsed[0].sources, vec!["s-phase1", "s-phase2"]);
        assert!(parsed[0].body.contains("write to a .tmp file first"));
    }

    #[test]
    fn multi_session_invariant_requires_at_least_two_distinct_sessions() {
        let mut available = HashSet::new();
        available.insert("s-1".to_string());
        available.insert("s-2".to_string());

        let single_source = ConsolidatedProposal {
            agent: "zed".into(),
            slug: "pattern".into(),
            folder: "knowledge".into(),
            summary: "summary".into(),
            keys: vec!["key".into()],
            sources: vec!["s-1".into()],
            body: "body".into(),
        };
        assert!(validate_multi_session_evidence(&single_source, &available).is_err());

        let duplicate_source = ConsolidatedProposal {
            agent: "zed".into(),
            slug: "pattern".into(),
            folder: "knowledge".into(),
            summary: "summary".into(),
            keys: vec!["key".into()],
            sources: vec!["s-1".into(), "s-1".into()],
            body: "body".into(),
        };
        assert!(validate_multi_session_evidence(&duplicate_source, &available).is_err());

        let valid = ConsolidatedProposal {
            agent: "zed".into(),
            slug: "pattern".into(),
            folder: "knowledge".into(),
            summary: "summary".into(),
            keys: vec!["key".into()],
            sources: vec!["s-1".into(), "s-2".into()],
            body: "body".into(),
        };
        assert!(validate_multi_session_evidence(&valid, &available).is_ok());

        let unknown_source = ConsolidatedProposal {
            agent: "zed".into(),
            slug: "pattern".into(),
            folder: "knowledge".into(),
            summary: "summary".into(),
            keys: vec!["key".into()],
            sources: vec!["s-1".into(), "s-ghost".into()],
            body: "body".into(),
        };
        assert!(validate_multi_session_evidence(&unknown_source, &available).is_err());
    }

    #[test]
    fn consolidation_outcome_as_json() {
        let outcome = ConsolidationOutcome {
            agent: "zed".into(),
            sessions_consulted: 3,
            proposals_generated: 1,
            rejected_evidence: vec![("hallucinated".into(), "fake session".into())],
            decided: Vec::new(),
        };
        let val = outcome.as_json();
        assert_eq!(val.get("agent"), Some(&crate::json::Value::Str("zed".into())));
        assert_eq!(val.get("sessions_consulted"), Some(&crate::json::Value::Num(3.0)));
        assert_eq!(val.get("proposals_generated"), Some(&crate::json::Value::Num(1.0)));
    }
}
