//! The gate an alias has to pass before it may be written.
//!
//! # Why a gate exists at all, and why it is this shape
//!
//! `kb-aliases.txt` used to be writable only by a person, and the reason travelled with
//! the rule: a machine that appends to it on evidence it also generated closes that loop
//! with nobody in it. That argument was weaker than it looked. **The evidence is not
//! generated by the machine.** `kb-misses.txt` records questions a real person actually
//! asked and the base actually failed, which is as external as evidence gets here.
//!
//! The argument that does hold is about signal, and it is structural:
//!
//! - `Memory::recall_loss` returns `None` unless the verdict is `Nothing`, so **only a
//!   total miss is ever logged.** A guess is not. A confident hit on the wrong file is
//!   not.
//! - Alias expansion is additive, so an alias **cannot** cause a miss. It can only ever
//!   cause a confident hit on something else.
//!
//! Put together: the only feedback this system keeps is blind to the only damage an alias
//! can do. A writer fed by that log would improve the column it can see and quietly
//! degrade the one it cannot, and nothing would record it. That is not hypothetical.
//! `interface = design system` sat in one base for weeks pulling every question carrying
//! the word `interface` to its author, and produced zero lines in the miss log, because it
//! never made anything missing.
//!
//! So the loop may close, and what closes it is not a second model. It is a measurement.
//!
//! # The two sides, and why one of them is not enough
//!
//! **Efficacy.** The question the candidate was proposed for has to stop missing. Without
//! this, the gate admits any line that happens to be harmless, and harmless is not the
//! same as useful.
//!
//! **No harm.** No deterministic column of `kb eval` may drop. Without this, the writer
//! optimises recall and pays for it in precision, which is the exact failure above.
//!
//! Both are required. Either one alone admits a class of line nobody wants.
//!
//! # Why the gate refuses to look at the classifier
//!
//! [`Scores`] carries the keyword columns and the abstention failure, and deliberately not
//! `routed_hits` or anything the classifier touches. A gate that shells out to a model
//! gives a different answer on Tuesday, and an admission record that cannot be reproduced
//! is an admission record that cannot be audited. The model's place in this loop is to
//! **propose**; the arithmetic decides. That is the division ADR-0018 already draws through
//! retrieval, applied one layer up.

use crate::{eval, memory::Memory};
use std::path::{Path, PathBuf};

/// A proposed alias line, and everything needed to judge it.
#[derive(Debug, Clone)]
pub struct Candidate {
    /// The left side: the word a real question used.
    pub alias: String,
    /// The right side: the word the base already knows.
    pub canonical: String,
    /// The base whose `kb-aliases.txt` would carry the line, by directory name.
    pub base: String,
    /// The logged question this was proposed for. The efficacy side runs against it, so a
    /// candidate with no question behind it cannot be judged and is refused.
    pub because: String,
}

impl Candidate {
    pub fn line(&self) -> String {
        format!("{} = {}", self.alias.trim(), self.canonical.trim())
    }

    /// Refuses the shapes that cannot help, before any measurement is paid for.
    pub fn obvious_problem(&self) -> Option<&'static str> {
        if self.alias.trim().is_empty() || self.canonical.trim().is_empty() {
            return Some("an empty side");
        }
        if self.alias.trim().eq_ignore_ascii_case(self.canonical.trim()) {
            return Some("both sides are the same word, so it expands to itself");
        }
        if self.because.trim().is_empty() {
            return Some("no logged question behind it, so efficacy cannot be tested");
        }
        if self.alias.contains('=') || self.canonical.contains('=') {
            return Some("an equals sign inside a side, which the parser splits on");
        }
        None
    }
}

/// The columns the gate judges, and only these.
///
/// Every one is produced without a model, so the same candidate judged twice gets the same
/// verdict. See the module header for why that matters more than breadth here.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Scores {
    /// Top-1 correct file, keyword scorer.
    pub file: usize,
    /// Correct owner, the deterministic fold. This is what `kb boot` falls back to.
    pub agent: usize,
    /// Rows the set says to decline that were answered as a confident hit. **Lower is
    /// better**, which is why its comparison below runs the other way round.
    pub answered_when_it_should_decline: usize,
}

impl Scores {
    /// The no-harm side. Not "did it improve", which is the different question the
    /// efficacy side answers.
    pub fn no_worse_than(&self, before: &Scores) -> bool {
        self.file >= before.file
            && self.agent >= before.agent
            && self.answered_when_it_should_decline <= before.answered_when_it_should_decline
    }

    pub fn line(&self) -> String {
        format!(
            "file {} agent {} answered-when-should-decline {}",
            self.file, self.agent, self.answered_when_it_should_decline
        )
    }
}

#[derive(Debug, Clone)]
pub struct Verdict {
    pub admitted: bool,
    /// Why, in the words a person reads beside the line that got written.
    pub reason: String,
    pub before: Scores,
    pub after: Scores,
    /// Whether the question it was proposed for stopped missing.
    pub fixes_its_own_miss: bool,
}

impl Verdict {
    /// The comment written above an admitted line, so the measurement travels with the
    /// decision instead of living in a terminal nobody kept.
    pub fn provenance(&self, c: &Candidate, on: &str) -> String {
        format!(
            "# admitted {on} by `kb misses --apply`. Proposed for: {}\n#   before: {}\n#   after:  {}\n",
            c.because.trim(),
            self.before.line(),
            self.after.line()
        )
    }
}

fn score(memory: &Memory, rows: &[(String, Vec<String>)], top: usize) -> Scores {
    let s = eval::summarise(&eval::run(memory, rows, top));
    Scores {
        file: s.keyword_hits,
        agent: s.keyword_agent_hits,
        answered_when_it_should_decline: s.abstention_answered,
    }
}

/// Opens the base twice, once as it stands and once with the candidate held in memory, and
/// answers whether the line may be written.
///
/// Opening twice is not free and is not optimised, deliberately: this runs when somebody
/// asks to change the routing layer, not when somebody asks a question.
pub fn judge(
    paths: &[&Path],
    all: bool,
    gold: &[(String, Vec<String>)],
    top: usize,
    c: &Candidate,
) -> Result<Verdict, String> {
    if let Some(problem) = c.obvious_problem() {
        return Err(format!("`{}` is refused before measuring: {problem}", c.line()));
    }

    let plain = Memory::open(paths, all).map_err(|e| e.to_string())?;
    let before = score(&plain, gold, top);

    // The question has to be missing *now*, or "it stopped missing" proves nothing.
    let missed_before = plain.ask(&c.because, top).confidence.verdict;

    let widened = Memory::open(paths, all).map_err(|e| e.to_string())?.with_extra_aliases(vec![(
        c.alias.trim().to_string(),
        c.canonical.trim().to_string(),
    )]);
    let after = score(&widened, gold, top);
    let found_after = widened.ask(&c.because, top).confidence.verdict;

    let was_missing = missed_before == crate::memory::Verdict::Nothing;
    let fixes_its_own_miss = was_missing && found_after != crate::memory::Verdict::Nothing;
    let no_harm = after.no_worse_than(&before);

    let reason = if fixes_its_own_miss && no_harm {
        "admitted: the question it was proposed for stops missing, and no column dropped"
            .to_string()
    } else if !was_missing {
        format!(
            "refused: `{}` does not miss today, so there is nothing for this line to fix",
            c.because.trim()
        )
    } else if !fixes_its_own_miss {
        format!("refused: `{}` still finds nothing with the line applied", c.because.trim())
    } else {
        format!(
            "refused: it fixes its own question and costs elsewhere. before {} / after {}",
            before.line(),
            after.line()
        )
    };

    Ok(Verdict { admitted: fixes_its_own_miss && no_harm, reason, before, after, fixes_its_own_miss })
}

/// Appends an admitted line to the base that will carry it, with its measurement above it.
///
/// Refuses to write the same left side twice. Expansion is additive, so a duplicate is not
/// an error any reader would ever see, which is exactly why it has to be caught here.
pub fn write_line(
    base_root: &Path,
    c: &Candidate,
    v: &Verdict,
    on: &str,
) -> Result<PathBuf, String> {
    if !v.admitted {
        return Err("refusing to write a line the gate did not admit".to_string());
    }
    let path = base_root.join("kb-aliases.txt");
    let existing = std::fs::read_to_string(&path).unwrap_or_default();
    let already = existing
        .lines()
        .map(|l| l.split('#').next().unwrap_or("").trim())
        .filter_map(|l| l.split_once('='))
        .any(|(a, _)| a.trim().eq_ignore_ascii_case(c.alias.trim()));
    if already {
        return Err(format!("`{}` already has a line in {}", c.alias.trim(), path.display()));
    }

    let mut out = existing;
    if !out.is_empty() && !out.ends_with('\n') {
        out.push('\n');
    }
    out.push('\n');
    out.push_str(&v.provenance(c, on));
    out.push_str(&c.line());
    out.push('\n');
    std::fs::write(&path, out).map_err(|e| format!("cannot write {}: {e}", path.display()))?;
    Ok(path)
}

/// Where refusals are counted, beside `kb-misses.txt`.
///
/// Its own file rather than `kb-rejections.txt`, because that one carries promote's shape
/// (agent, slug, lens) and two shapes in one log is a log nobody can parse. The discipline
/// is the same and it is the reason both exist: **a proposer that keeps offering the same
/// refused line is a signal about the proposer**, and that signal only survives if refusals
/// are counted rather than printed once into a terminal.
pub const ALIAS_REJECTIONS_TXT: &str = "kb-alias-rejections.txt";

const REJECT_HEADER: &str = "\
# Alias lines the gate refused, most refused first.
#
# One line per distinct line: count, first seen, last seen, the proposed line, then why.
# A line refused repeatedly is a signal about whoever keeps proposing it, which is the
# whole reason these are counted instead of printed once.
#
# Not committed anywhere. These come from real questions asked by a real person.
";

/// Appends one refusal, folding a repeat into a count rather than a second line.
pub fn record_refusal(fleet_root: &Path, c: &Candidate, reason: &str, today: &str) {
    let path = fleet_root.join(ALIAS_REJECTIONS_TXT);
    let key = c.line();
    let existing = std::fs::read_to_string(&path).unwrap_or_default();
    let mut rows: Vec<(u32, String, String, String, String)> = Vec::new();
    let mut folded = false;

    for line in existing.lines() {
        if line.starts_with('#') || line.trim().is_empty() {
            continue;
        }
        let p: Vec<&str> = line.split('\t').collect();
        if p.len() < 5 {
            continue;
        }
        let count: u32 = p[0].trim().parse().unwrap_or(1);
        let (first, last, one, why) =
            (p[1].to_string(), p[2].to_string(), p[3].to_string(), p[4].to_string());
        if one == key {
            folded = true;
            rows.push((count + 1, first, today.to_string(), one, why));
        } else {
            rows.push((count, first, last, one, why));
        }
    }
    if !folded {
        rows.push((1, today.to_string(), today.to_string(), key, reason.replace('\t', " ")));
    }
    rows.sort_by(|a, b| b.0.cmp(&a.0));

    let mut out = String::from(REJECT_HEADER);
    for (n, first, last, one, why) in rows {
        out.push_str(&format!("{n}\t{first}\t{last}\t{one}\t{why}\n"));
    }
    let _ = std::fs::write(&path, out);
}

/// What came back from the proposer, with the three outcomes kept apart.
///
/// **They were one outcome for the length of one run and that was a defect.** The first
/// version returned an empty `Vec` for all three, so a report reading `proposed 0` could
/// mean the model declined, or that it answered nothing usable, or that it never ran at
/// all. A loop whose failure looks exactly like its considered judgement is a loop nobody
/// can debug, and this one is meant to run unattended.
#[derive(Debug)]
pub enum Proposal {
    /// The command failed, or produced nothing. Not a decision, an outage.
    ModelSilent,
    /// The model answered NONE: no alias here would honestly help. A real result.
    Declined,
    /// What it offered, and how many of its lines were dropped as unparseable. A rising
    /// `dropped` is a signal about the proposer rather than about the base.
    Lines { candidates: Vec<Candidate>, dropped: usize },
}

/// Asks the configured model for candidate lines for one missed question.
///
/// **The model proposes and never decides.** It sees the question, the vocabulary the base
/// offered back, and the files the text scorer nearly caught it with, each with the keys it
/// declares. It answers in one fixed shape and anything that does not parse is dropped
/// rather than repaired, because a parser that guesses at a malformed proposal is a second
/// proposer nobody reviewed.
pub fn propose(
    model: &crate::classify::Classifier,
    root: &Path,
    question: &str,
    looked_like: &[String],
    near: &[crate::memory::NearMiss],
) -> Proposal {
    let mut prompt = String::new();
    prompt.push_str(
        "You propose alias lines for a keyword router. An alias expands a query term into \
         another term, additively: the original words always survive.\n\n",
    );
    prompt.push_str(&format!("The question that found nothing:\n  {question}\n\n"));
    if !looked_like.is_empty() {
        prompt.push_str(&format!(
            "Vocabulary the base offered back, by character overlap only, so it reaches a \
             typo or a cognate and never a translation:\n  {}\n\n",
            looked_like.join(", ")
        ));
    }
    prompt.push_str("Files the text scorer nearly caught it with, and the keys each declares:\n");
    for n in near {
        prompt.push_str(&format!(
            "  {}/{}  keyword score {:.2}\n    keys: {}\n",
            n.base,
            n.rel,
            n.keyword_score,
            if n.keys.is_empty() { "none".to_string() } else { n.keys.join(", ") }
        ));
    }
    prompt.push_str(
        "\nA keyword score of 0.00 means the question's words are in that file's body and \
         not on its `Search for:` line, which is the case an alias fixes.\n\n\
         Answer with one line per proposal and nothing else, in exactly this shape, tab \
         separated:\n\n  base<TAB>alias<TAB>canonical\n\n\
         `base` is the agent directory name whose kb-aliases.txt would carry it. `alias` is \
         a term from the question. `canonical` is a term that file already declares. Both \
         sides must be more than one word after stopwords, or the term reaches neither \
         index. Propose at most three. If no alias would honestly help, answer exactly \
         NONE.\n",
    );

    let Some(reply) = crate::promote::ask_model(model, root, &prompt) else {
        return Proposal::ModelSilent;
    };
    if reply.trim().is_empty() {
        return Proposal::ModelSilent;
    }
    if reply.trim().eq_ignore_ascii_case("NONE") {
        return Proposal::Declined;
    }

    let mut candidates = Vec::new();
    let mut dropped = 0usize;
    for l in reply.lines() {
        if l.trim().is_empty() {
            continue;
        }
        let p: Vec<&str> = l.split('\t').map(|s| s.trim()).collect();
        if p.len() != 3 || p.iter().any(|s| s.is_empty()) {
            dropped += 1;
            continue;
        }
        let c = Candidate {
            base: p[0].to_string(),
            alias: p[1].to_string(),
            canonical: p[2].to_string(),
            because: question.to_string(),
        };
        if c.obvious_problem().is_some() {
            dropped += 1;
            continue;
        }
        candidates.push(c);
    }
    candidates.truncate(3);
    if candidates.is_empty() && dropped == 0 {
        return Proposal::Declined;
    }
    Proposal::Lines { candidates, dropped }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn candidate(alias: &str, canonical: &str, because: &str) -> Candidate {
        Candidate {
            alias: alias.into(),
            canonical: canonical.into(),
            base: "zed".into(),
            because: because.into(),
        }
    }

    #[test]
    fn a_side_that_expands_to_itself_is_refused_before_anything_is_measured() {
        let c = candidate("deploy", "Deploy", "como faco um deploy");
        assert_eq!(
            c.obvious_problem(),
            Some("both sides are the same word, so it expands to itself")
        );
    }

    #[test]
    fn a_candidate_with_no_question_behind_it_cannot_be_judged() {
        let c = candidate("frete", "entrega", "   ");
        assert_eq!(
            c.obvious_problem(),
            Some("no logged question behind it, so efficacy cannot be tested")
        );
    }

    /// The asymmetry that the whole module exists for, asserted rather than described.
    /// Two columns want to go up and one wants to go down, and reading that third one the
    /// same way as the other two admits exactly the lines this gate is here to stop.
    #[test]
    fn the_abstention_column_is_compared_the_other_way_round() {
        let before = Scores { file: 10, agent: 20, answered_when_it_should_decline: 2 };
        let more_wrong_answers =
            Scores { file: 10, agent: 20, answered_when_it_should_decline: 3 };
        let fewer_wrong_answers =
            Scores { file: 10, agent: 20, answered_when_it_should_decline: 1 };
        assert!(!more_wrong_answers.no_worse_than(&before), "answering more is harm");
        assert!(fewer_wrong_answers.no_worse_than(&before), "answering fewer is not");
    }

    #[test]
    fn any_single_column_dropping_is_enough_to_refuse() {
        let before = Scores { file: 10, agent: 20, answered_when_it_should_decline: 2 };
        assert!(!Scores { file: 9, agent: 20, answered_when_it_should_decline: 2 }
            .no_worse_than(&before));
        assert!(!Scores { file: 10, agent: 19, answered_when_it_should_decline: 2 }
            .no_worse_than(&before));
        assert!(Scores { file: 10, agent: 20, answered_when_it_should_decline: 2 }
            .no_worse_than(&before), "unchanged is not harm");
    }

    /// A line nobody can trace back to a measurement is a line the next reader has to take
    /// on trust, which is the state this whole change exists to leave behind.
    #[test]
    fn an_admitted_line_carries_the_numbers_that_admitted_it() {
        let c = candidate("estorno", "reembolso", "quanto tempo demora o estorno");
        let v = Verdict {
            admitted: true,
            reason: "admitted".into(),
            before: Scores { file: 10, agent: 20, answered_when_it_should_decline: 2 },
            after: Scores { file: 11, agent: 20, answered_when_it_should_decline: 2 },
            fixes_its_own_miss: true,
        };
        let text = v.provenance(&c, "2026-09-03");
        assert!(text.contains("quanto tempo demora o estorno"), "the question travels: {text}");
        assert!(text.contains("file 10"), "the before travels: {text}");
        assert!(text.contains("file 11"), "the after travels: {text}");
    }

    #[test]
    fn a_refused_verdict_cannot_be_written_even_by_calling_the_writer_directly() {
        let c = candidate("estorno", "reembolso", "quanto tempo demora o estorno");
        let v = Verdict {
            admitted: false,
            reason: "refused".into(),
            before: Scores { file: 10, agent: 20, answered_when_it_should_decline: 2 },
            after: Scores { file: 9, agent: 20, answered_when_it_should_decline: 2 },
            fixes_its_own_miss: true,
        };
        let err = write_line(Path::new("."), &c, &v, "2026-09-03").unwrap_err();
        assert!(err.contains("did not admit"), "{err}");
    }
}
