import { defineConfig, type Plugin } from "vite";
import { resolve, relative } from "node:path";
import { readdirSync, existsSync } from "node:fs";

// Pages are discovered, never enumerated. A page is a folder with an
// index.html in it, at any depth under one of the folders named below, and a
// folder should never also have to be a line in a build config: the blog
// pages are generated by tools/build-posts.mjs before this file is read, and
// the docs are hand-written, but the rule is the same for both. A file with
// any other name is not a page and is not built, which is what keeps
// docs/_skeleton.html, the page the writers copy from, out of the artifact.
// The key is the folder path with dashes (docs, docs-concepts, blog-<slug>),
// the same keys the earlier blog-only walker produced.
function pagesUnder(folder: string): Record<string, string> {
  const root = resolve(__dirname, folder);
  const out: Record<string, string> = {};
  if (!existsSync(root)) return out;
  const walk = (dir: string) => {
    const index = resolve(dir, "index.html");
    if (existsSync(index)) out[relative(__dirname, dir).split(/[\/]/).join("-")] = index;
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      if (entry.isDirectory()) walk(resolve(dir, entry.name));
    }
  };
  walk(root);
  return out;
}

// The folders whose pages are discovered. A new top-level section is one word
// here and a folder on disk; the pages at the root (index, 404) and the three
// single documents stay listed by hand below because they are not sections.
const SECTIONS = ["docs", "blog"];

// Preload the body face (400 normal) only. Its URL carries a content hash that
// exists only at build time, so the tag is injected here rather than written in
// the HTML. The italic and 600 faces are not preloaded: they appear below the
// fold and may arrive with the stylesheet.
function preloadBodyFace(): Plugin {
  return {
    name: "preload-body-face",
    transformIndexHtml: {
      order: "post",
      handler(html, ctx) {
        const file = Object.keys(ctx.bundle ?? {}).find((name) =>
          /eb-garamond-latin-400-normal.*\.woff2$/.test(name),
        );
        if (!file) return html;
        return {
          html,
          tags: [
            {
              tag: "link",
              attrs: {
                rel: "preload",
                as: "font",
                type: "font/woff2",
                // Required on font preloads even same-origin, per the spec.
                crossorigin: "",
                href: "/" + file,
              },
              injectTo: "head-prepend",
            },
          ],
        };
      },
    },
  };
}

// No framework. Hand-written HTML, the generated writing, one stylesheet and
// the three scripts in public/ (theme.js on every page, anim.js and
// subscribe.js on the front page only, by owner directive), which vite copies
// unhashed. The build exists to compile the stylesheet, hash the asset
// filenames (which is what makes the server's `immutable` cache header
// honest), and minify.
export default defineConfig({
  build: {
    rollupOptions: {
      input: {
        index: resolve(__dirname, "index.html"),
        404: resolve(__dirname, "404.html"),
        privacy: resolve(__dirname, "privacy/index.html"),
        terms: resolve(__dirname, "terms/index.html"),
        benchmarks: resolve(__dirname, "benchmarks/index.html"),
        ...Object.assign({}, ...SECTIONS.map(pagesUnder)),
      },
    },
  },
  plugins: [preloadBodyFace()],
});
